#!/bin/sh
# install-nbr.sh — idempotent installer for the nbr binary
# Shared between Claude and Codex plugins.
#
# Usage: install-nbr.sh <install_dir>
#   install_dir: directory to place the nbr binary (e.g. ${CLAUDE_PLUGIN_DATA}/bin)
#
# Env vars honoured:
#   NBR_VERSION         — install a specific version, e.g. 1.0.3 (default: the
#                         latest published platform release, resolved at runtime)
#   NBR_LOCAL_BIN       — path to a locally-built nbr binary; skips network download
#   NBR_WRAPPER_API_URL — when non-empty, bake an UNCONDITIONAL
#                         `export NBR_API_URL=<value>` into the generated wrapper
#                         (sandbox/harness use only; unset for real end-user
#                         installs). See write_nbr_wrapper below.
#   CLAUDE_PLUGIN_DATA / PLUGIN_DATA — used if install_dir not passed
#
# NOTE: GitHub Releases for nbr are produced by the cargo-dist CI pipeline.
# If the release/asset does not yet exist, this script prints a friendly notice
# and exits 0 (it does NOT hard-fail the hook).

set -e

REPO="replygirl/nearest-neighbor"

# ── Resolve the version/tag to install ──────────────────────────────────────────
# An explicit NBR_VERSION wins (used by e2e and local source builds via
# NBR_LOCAL_BIN). Otherwise resolve the latest published platform release tag from
# GitHub at runtime — mirroring apps/web/public/install.sh. We hit /releases (not
# /releases/latest) so prereleases count: the full platform ships under a single
# v<n>.<n>.<n> tag (no separate cli-v* tag) and the newest release may be a
# prerelease. Hardcoding a literal default here is what stranded every install on
# the asset-less v0.1.0.
#
# A local-bin install needs no network resolution (its version is whatever the
# provided binary reports), so we only reach out to GitHub on the download path.
NBR_VERSION="${NBR_VERSION:-}"
if [ -z "${NBR_VERSION}" ] && [ -z "${NBR_LOCAL_BIN:-}" ]; then
  GH_RELEASE_TAG=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases" 2>/dev/null \
    | grep -o '"tag_name": *"v[^"]*"' \
    | head -1 \
    | grep -o 'v[^"]*' || true)
  if [ -z "${GH_RELEASE_TAG}" ]; then
    echo "[nearest-neighbor] Could not determine the latest nbr release (offline or GitHub unreachable)."
    echo "[nearest-neighbor] To install from source: cd nearest-neighbor/apps/cli && cargo install --path ."
    exit 0
  fi
  NBR_VERSION="${GH_RELEASE_TAG#v}"
else
  GH_RELEASE_TAG="v${NBR_VERSION}"
fi

# Resolve install dir: argument → CLAUDE_PLUGIN_DATA/bin → PLUGIN_DATA/bin
if [ -n "$1" ]; then
  INSTALL_DIR="$1"
elif [ -n "${CLAUDE_PLUGIN_DATA}" ]; then
  INSTALL_DIR="${CLAUDE_PLUGIN_DATA}/bin"
elif [ -n "${PLUGIN_DATA}" ]; then
  INSTALL_DIR="${PLUGIN_DATA}/bin"
else
  echo "[nearest-neighbor] ERROR: install_dir not specified and CLAUDE_PLUGIN_DATA/PLUGIN_DATA not set." >&2
  exit 1
fi

NBR_BIN="${INSTALL_DIR}/nbr"

# ── Wrapper writer ──────────────────────────────────────────────────────────────
# Writes the portable nbr wrapper to <path>. The wrapper is scope-aware:
# per-project when the plugin is project-enabled (.claude/settings*.json or
# .codex/config.toml), else one shared dir. Defaults NBR_NO_KEYRING so config
# isolation is in effect regardless of which host (Claude Code, Codex, or any
# other agent) invokes it — no env-file mechanism required.
#
# When NBR_WRAPPER_API_URL is set at install time, an UNCONDITIONAL
# `export NBR_API_URL=<value>` line is baked in (NOT a ${VAR:-...} default) so a
# sandbox's local API target survives login-shell profile reloads (e.g.
# `zsh -lc`, used by some agent hosts) that can clobber an inherited
# NBR_API_URL and silently fall back to the production default. When the var is
# unset (real end-user plugin installs) no api-url line is emitted — preserving
# the prior behavior of honoring the inherited environment.
write_nbr_wrapper() {
  wrapper_target="$1"
  cat > "$wrapper_target" <<'WRAP'
#!/bin/sh
# nbr wrapper — scope-aware config dir: per-project when plugin is project-enabled, else shared.
# DO NOT EDIT — regenerated by install-nbr.sh on each install.
SELF_DIR=$(cd "$(dirname "$0")" && pwd)
PLUGIN_DATA=$(cd "${SELF_DIR}/.." && pwd)

# Detect whether the plugin is project-enabled in this tree.
# If so, use a per-project dir under agents/; else fall back to one shared dir.
# Precedence: explicit NBR_CONFIG_DIR override wins; else walk up from
# CLAUDE_PROJECT_DIR (or $PWD) looking for .claude/settings*.json or
# .codex/config.toml that enable nearest-neighbor@nearest-neighbor.
if [ -z "${NBR_CONFIG_DIR:-}" ]; then
  __plugin_id="nearest-neighbor@nearest-neighbor"
  __start="${CLAUDE_PROJECT_DIR:-$(pwd)}"
  __install=""
  __d="${__start}"
  while [ -n "${__d}" ] && [ "${__d}" != "/" ]; do
    if [ -n "${HOME:-}" ] && [ "${__d}" = "${HOME}" ]; then break; fi
    for __sf in "${__d}/.claude/settings.json" "${__d}/.claude/settings.local.json"; do
      if [ -f "${__sf}" ] && grep -q "\"${__plugin_id}\"[[:space:]]*:[[:space:]]*true" "${__sf}" 2>/dev/null; then
        __install="${__d}"; break
      fi
    done
    [ -n "${__install}" ] && break
    if [ -f "${__d}/.codex/config.toml" ] && awk '
        /^[[:space:]]*\[plugins\..*nearest-neighbor/ { inblk=1; next }
        /^[[:space:]]*\[/ { inblk=0 }
        inblk && /^[[:space:]]*enabled[[:space:]]*=[[:space:]]*true/ { found=1 }
        END { exit(found?0:1) }
      ' "${__d}/.codex/config.toml" 2>/dev/null; then
      __install="${__d}"; break
    fi
    __d=$(dirname "${__d}")
  done
  if [ -n "${__install}" ]; then
    __base=$(basename "${__install}" | tr -cd 'A-Za-z0-9_.-')
    if command -v shasum >/dev/null 2>&1; then
      __hash=$(printf '%s' "${__install}" | shasum -a 256 | cut -c1-12)
    elif command -v sha256sum >/dev/null 2>&1; then
      __hash=$(printf '%s' "${__install}" | sha256sum | cut -c1-12)
    else
      __hash=$(printf '%s' "${__install}" | cksum | tr -cd '0-9' | cut -c1-12)
    fi
    NBR_CONFIG_DIR="${PLUGIN_DATA}/agents/${__base}-${__hash}/nbr"
  else
    NBR_CONFIG_DIR="${PLUGIN_DATA}/nbr"
  fi
fi
export NBR_CONFIG_DIR
export NBR_NO_KEYRING="${NBR_NO_KEYRING:-1}"
WRAP
  if [ -n "${NBR_WRAPPER_API_URL:-}" ]; then
    printf 'export NBR_API_URL="%s"\n' "${NBR_WRAPPER_API_URL}" >> "$wrapper_target"
  fi
  cat >> "$wrapper_target" <<'WRAP'
mkdir -p "${NBR_CONFIG_DIR}" 2>/dev/null || true
if [ "${1:-}" = "--print-config-dir" ]; then
  printf '%s\n' "${NBR_CONFIG_DIR}"
  exit 0
fi
exec "${SELF_DIR}/.nbr-real" "$@"
WRAP
  chmod +x "$wrapper_target"
}

# ── Idempotency check ──────────────────────────────────────────────────────────
if [ -x "${NBR_BIN}" ]; then
  INSTALLED_VERSION=$("${NBR_BIN}" --version 2>/dev/null | awk '{print $NF}' || true)
  if [ "${INSTALLED_VERSION}" = "${NBR_VERSION}" ]; then
    echo "[nearest-neighbor] nbr ${NBR_VERSION} already installed at ${NBR_BIN}. Skipping."
    exit 0
  fi
fi

# ── Local/source-build install path ───────────────────────────────────────────
# If NBR_LOCAL_BIN is set and points to an executable file, install it directly
# without downloading from GitHub Releases. Used by e2e tests and when building
# nbr from source (cd apps/cli && cargo build --release, then set NBR_LOCAL_BIN).
if [ -n "${NBR_LOCAL_BIN}" ]; then
  if [ ! -f "${NBR_LOCAL_BIN}" ] || [ ! -x "${NBR_LOCAL_BIN}" ]; then
    echo "[nearest-neighbor] ERROR: NBR_LOCAL_BIN='${NBR_LOCAL_BIN}' is not an executable file." >&2
    exit 1
  fi
  echo "[nearest-neighbor] Installing nbr from local binary: ${NBR_LOCAL_BIN}"
  mkdir -p "${INSTALL_DIR}"
  NBR_REAL="${INSTALL_DIR}/.nbr-real"
  cp "${NBR_LOCAL_BIN}" "${NBR_REAL}"
  chmod +x "${NBR_REAL}"
  # Write the same portable wrapper the download path writes
  write_nbr_wrapper "${NBR_BIN}"
  # ── Verify ────────────────────────────────────────────────────────────────────
  VERIFIED_VERSION=$("${NBR_BIN}" --version 2>/dev/null | awk '{print $NF}' || true)
  if [ "${VERIFIED_VERSION}" = "${NBR_VERSION}" ]; then
    echo "[nearest-neighbor] nbr ${NBR_VERSION} installed successfully at ${NBR_BIN} (local build)."
  else
    echo "[nearest-neighbor] WARNING: installed nbr reports version '${VERIFIED_VERSION}' (expected '${NBR_VERSION}')." >&2
  fi
  exit 0
fi

# ── Detect OS + arch → Rust target triple ─────────────────────────────────────
OS=$(uname -s 2>/dev/null || echo "Unknown")
ARCH=$(uname -m 2>/dev/null || echo "Unknown")

case "${OS}" in
  Darwin)
    case "${ARCH}" in
      arm64)  TRIPLE="aarch64-apple-darwin" ;;
      x86_64) TRIPLE="x86_64-apple-darwin" ;;
      *)
        echo "[nearest-neighbor] Unsupported macOS arch: ${ARCH}. Cannot install nbr." >&2
        exit 0
        ;;
    esac
    ;;
  Linux)
    case "${ARCH}" in
      x86_64)  TRIPLE="x86_64-unknown-linux-musl" ;;
      aarch64) TRIPLE="aarch64-unknown-linux-musl" ;;
      *)
        echo "[nearest-neighbor] Unsupported Linux arch: ${ARCH}. Cannot install nbr." >&2
        exit 0
        ;;
    esac
    ;;
  *)
    echo "[nearest-neighbor] Unsupported OS: ${OS}. Use install-nbr.ps1 on Windows." >&2
    exit 0
    ;;
esac

ASSET="nbr-${TRIPLE}.tar.xz"
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${GH_RELEASE_TAG}/${ASSET}"

echo "[nearest-neighbor] Installing nbr ${NBR_VERSION} for ${TRIPLE}..."

# ── Create install dir ─────────────────────────────────────────────────────────
mkdir -p "${INSTALL_DIR}"

# ── Download + extract ─────────────────────────────────────────────────────────
TMP_DIR=$(mktemp -d)
trap 'rm -rf "${TMP_DIR}"' EXIT

ARCHIVE="${TMP_DIR}/${ASSET}"

# Try curl first, then wget
if command -v curl >/dev/null 2>&1; then
  HTTP_STATUS=$(curl -sL --write-out "%{http_code}" -o "${ARCHIVE}" "${DOWNLOAD_URL}")
elif command -v wget >/dev/null 2>&1; then
  if wget -q -O "${ARCHIVE}" "${DOWNLOAD_URL}" 2>/dev/null; then
    HTTP_STATUS="200"
  else
    HTTP_STATUS="404"
  fi
else
  echo "[nearest-neighbor] Neither curl nor wget is available. Cannot download nbr." >&2
  exit 0
fi

if [ "${HTTP_STATUS}" != "200" ]; then
  echo "[nearest-neighbor] nbr ${NBR_VERSION} release not yet available (HTTP ${HTTP_STATUS})."
  echo "[nearest-neighbor] GitHub Releases are produced by the cargo-dist CI pipeline — check back after the first release."
  echo "[nearest-neighbor] To install from source: cd nearest-neighbor/apps/cli && cargo install --path ."
  exit 0
fi

# Extract the binary
if command -v tar >/dev/null 2>&1; then
  tar -xJf "${ARCHIVE}" -C "${TMP_DIR}" 2>/dev/null || tar -xf "${ARCHIVE}" -C "${TMP_DIR}"
else
  echo "[nearest-neighbor] tar not found. Cannot extract nbr archive." >&2
  exit 0
fi

# Find the binary in the extracted contents
NBR_EXTRACTED=$(find "${TMP_DIR}" -name "nbr" -type f | head -1)
if [ -z "${NBR_EXTRACTED}" ]; then
  echo "[nearest-neighbor] Could not find nbr binary in downloaded archive." >&2
  exit 0
fi

# Install the real binary as .nbr-real
NBR_REAL="${INSTALL_DIR}/.nbr-real"
cp "${NBR_EXTRACTED}" "${NBR_REAL}"
chmod +x "${NBR_REAL}"

# ── Write portable wrapper script ──────────────────────────────────────────────
write_nbr_wrapper "${NBR_BIN}"

# ── Verify ─────────────────────────────────────────────────────────────────────
VERIFIED_VERSION=$("${NBR_BIN}" --version 2>/dev/null | awk '{print $NF}' || true)
if [ "${VERIFIED_VERSION}" = "${NBR_VERSION}" ]; then
  echo "[nearest-neighbor] nbr ${NBR_VERSION} installed successfully at ${NBR_BIN}."
else
  echo "[nearest-neighbor] WARNING: installed nbr reports version '${VERIFIED_VERSION}' (expected '${NBR_VERSION}')." >&2
fi
