#compdef nearest-neighbor-mise
# @generated by usage-cli from /dev/stdin
local curcontext="$curcontext"

_nearest_neighbor_mise() {
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
      echo >&2
      echo "Error: usage CLI not found. This is required for completions to work in nearest-neighbor-mise." >&2
      echo "See https://usage.jdx.dev for more information." >&2
      return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_nearest_neighbor_mise.spec"
  cat >| "$spec_file" <<'__USAGE_EOF__'
name nearest-neighbor-mise
bin stdin
cmd agents:bootstrap {
    flag --dry-run help="Print actions without executing (mutates nothing)"
}
cmd agents:clean {
    flag --name help="Clean one agent by name (or set NAME env var)"
    flag --all help="Clean every agent and sandbox/logs/ (or set ALL=1)"
}
cmd agents:fleet {
    flag --reset help="Pass --reset to agents:ready (run db:reset first)"
    flag --seed help="Pass --seed to agents:ready (run db:seed after reset)"
}
cmd agents:headless {
    flag --prompt help="Override the neutral nudge prompt (or set PROMPT env var)"
}
cmd agents:ready {
    flag --reset help="Run 'mise run db:reset' before polling"
    flag --seed help="Run 'mise run db:seed' after reset (non-empty deck backdrop)"
    flag --timeout help="Seconds to wait for /health (default 60)"
}
cmd agents:report {
    flag --name help="Limit report to one agent by name (or set NAME env var)"
    flag --since help="Only show DB activity since ISO timestamp (or set SINCE env var)"
}
cmd agents:setup
cmd agents:sync {
    flag --check help="Exit non-zero if files are out of sync (CI drift check)"
}
cmd agents:up
cmd dev:ensure-ports {
    flag --force help="Regenerate .dev/ports.env even if it already exists"
}
cmd docs:gen-spec
__USAGE_EOF__
  local -a completions=()
  while IFS= read -r line; do
    completions+=("$line")
  done < <(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}")
  _describe 'completions' completions -S ''
  return 0
}

if [ "$funcstack[1]" = "_nearest_neighbor_mise" ]; then
    _nearest_neighbor_mise "$@"
else
    compdef _nearest_neighbor_mise nearest-neighbor-mise
fi

# vim: noet ci pi sts=0 sw=4 ts=4
