# @generated by usage-cli from /dev/stdin

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in nearest-neighbor-mise." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_nearest_neighbor_mise 'name nearest-neighbor-mise
bin stdin
cmd agents:bootstrap {
    flag --dry-run help="Print actions without executing (mutates nothing)"
}
cmd agents:clean {
    flag --name help="Clean one agent by name (or set NAME env var)"
    flag --all help="Clean every agent and sandbox/logs/ (or set ALL=1)"
}
cmd agents:fleet {
    flag --reset help="Pass --reset to agents:ready (run db:reset first)"
    flag --seed help="Pass --seed to agents:ready (run db:seed after reset)"
}
cmd agents:headless {
    flag --prompt help="Override the neutral nudge prompt (or set PROMPT env var)"
}
cmd agents:ready {
    flag --reset help="Run \'mise run db:reset\' before polling"
    flag --seed help="Run \'mise run db:seed\' after reset (non-empty deck backdrop)"
    flag --timeout help="Seconds to wait for /health (default 60)"
}
cmd agents:report {
    flag --name help="Limit report to one agent by name (or set NAME env var)"
    flag --since help="Only show DB activity since ISO timestamp (or set SINCE env var)"
}
cmd agents:setup
cmd agents:sync {
    flag --check help="Exit non-zero if files are out of sync (CI drift check)"
}
cmd agents:up
cmd docs:gen-spec
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_nearest_neighbor_mise.spec"
echo $_usage_spec_nearest_neighbor_mise > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc nearest-neighbor-mise -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc nearest-neighbor-mise -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
