#!/bin/sh
# scripts/check-coverage.sh — coverage threshold gate for the nearest-neighbor monorepo
#
# Scans every workspace that has a `test:coverage` script in its package.json,
# reads its coverage/lcov.info output, and compares line/branch/function
# percentages against env-driven thresholds.
#
# Environment variables (all optional — defaults shown below):
#   NEAREST_NEIGHBOR_COVERAGE_MIN_LINES      Minimum line coverage %     (default: 95)
#   NEAREST_NEIGHBOR_COVERAGE_MIN_BRANCHES   Minimum branch coverage %   (default: 95)
#   NEAREST_NEIGHBOR_COVERAGE_MIN_FUNCTIONS  Minimum function coverage % (default: 95)
#
# Thresholds apply to every checked workspace and default to 95% across the
# board.  Note that Bun's LCOV emitter frequently reports 0 branch totals for
# pure-function modules; pct() returns 100.00 when the denominator is 0, so
# those modules still pass the 95% branch gate (they are not penalised for a
# reporter artefact).  Any module with real branches below 95% will fail.
#
# Skip list — workspaces exempted from the gate:
#   (none initially — add workspace paths here while test runner is being wired)
# TODO: remove workspaces from the skip list once their test runner is wired

set -eu

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

MIN_LINES="${NEAREST_NEIGHBOR_COVERAGE_MIN_LINES:-95}"
MIN_BRANCHES="${NEAREST_NEIGHBOR_COVERAGE_MIN_BRANCHES:-95}"
MIN_FUNCTIONS="${NEAREST_NEIGHBOR_COVERAGE_MIN_FUNCTIONS:-95}"

# Workspaces that are explicitly excluded from the coverage gate.
# Add workspace paths relative to the repo root.
SKIP_LIST=""

# ── helpers ──────────────────────────────────────────────────────────────────

# Returns "yes" if value < minimum (float comparison via awk)
below_threshold() {
  awk -v v="$1" -v m="$2" 'BEGIN { if (v + 0 < m + 0) print "yes"; else print "no" }'
}

# Sums a single LCOV metric across all records in a file
sum_metric() {
  awk -F ':' -v m="$1" '$1 == m { sum += $2 } END { print sum + 0 }' "$2"
}

# Compute percentage; returns "100.00" when denominator is 0
pct() {
  hit="$1"; total="$2"
  if [ "$total" -le 0 ]; then
    printf '100.00'
  else
    awk -v h="$hit" -v t="$total" 'BEGIN { printf "%.2f", (h / t) * 100 }'
  fi
}

is_skipped() {
  ws="$1"
  for skip in $SKIP_LIST; do
    if [ "$ws" = "$skip" ]; then
      return 0
    fi
  done
  return 1
}

# ── discover workspaces with test:coverage ───────────────────────────────────

# Collect workspaces (apps/* and packages/*) that declare a test:coverage
# script in their package.json.  This ensures we only gate on coverage that was
# actually generated by the preceding `bun run --filter '*' test:coverage` call.
CHECKED_WORKSPACES=''
for pkg_json in \
  "$REPO_ROOT"/apps/*/package.json \
  "$REPO_ROOT"/packages/*/package.json
do
  [ -f "$pkg_json" ] || continue
  # Check for "test:coverage" key in scripts
  if python3 -c "
import json, sys
d = json.load(open('$pkg_json'))
sys.exit(0 if 'test:coverage' in d.get('scripts', {}) else 1)
" 2>/dev/null; then
    ws_rel="$(dirname "$pkg_json" | sed "s|$REPO_ROOT/||")"
    CHECKED_WORKSPACES="$CHECKED_WORKSPACES $ws_rel"
  fi
done

if [ -z "$CHECKED_WORKSPACES" ]; then
  printf 'No workspaces with a test:coverage script found. Nothing to gate.\n'
  exit 0
fi

# ── process coverage files ────────────────────────────────────────────────────

PASS=0; FAIL=0; SKIP=0

# Table header
printf '\n'
printf '| %-22s | %7s | %9s | %11s | %s |\n' 'workspace' 'lines%' 'branches%' 'functions%' 'status'
printf '|%s|%s|%s|%s|%s|\n' \
  '------------------------' '---------' '-----------' '-------------' '--------'

for ws in $CHECKED_WORKSPACES; do
  # Skip explicitly exempted workspaces
  if is_skipped "$ws"; then
    printf '| %-22s | %7s | %9s | %11s | %s |\n' "$ws" 'n/a' 'n/a' 'n/a' 'skipped'
    SKIP=$((SKIP + 1))
    continue
  fi

  lcov="$REPO_ROOT/$ws/coverage/lcov.info"

  if [ ! -f "$lcov" ]; then
    printf '| %-22s | %7s | %9s | %11s | %s |\n' "$ws" '?' '?' '?' 'MISSING'
    printf 'ERROR: %s: coverage/lcov.info not found (run test:coverage first)\n' "$ws" >&2
    FAIL=$((FAIL + 1))
    continue
  fi

  lf=$(sum_metric LF "$lcov"); lh=$(sum_metric LH "$lcov")
  fnf=$(sum_metric FNF "$lcov"); fnh=$(sum_metric FNH "$lcov")
  brf=$(sum_metric BRF "$lcov"); brh=$(sum_metric BRH "$lcov")

  lines_pct=$(pct "$lh" "$lf")
  fn_pct=$(pct "$fnh" "$fnf")
  br_pct=$(pct "$brh" "$brf")

  ws_fail=0
  if [ "$(below_threshold "$lines_pct" "$MIN_LINES")" = 'yes' ]; then ws_fail=1; fi
  if [ "$(below_threshold "$br_pct" "$MIN_BRANCHES")" = 'yes' ]; then ws_fail=1; fi
  if [ "$(below_threshold "$fn_pct" "$MIN_FUNCTIONS")" = 'yes' ]; then ws_fail=1; fi

  if [ "$ws_fail" -eq 1 ]; then
    status='FAIL'
    FAIL=$((FAIL + 1))
  else
    status='pass'
    PASS=$((PASS + 1))
  fi

  printf '| %-22s | %7s | %9s | %11s | %s |\n' \
    "$ws" "${lines_pct}%" "${br_pct}%" "${fn_pct}%" "$status"
done

printf '\n'
printf 'Thresholds: lines >= %s%%  branches >= %s%%  functions >= %s%%\n' \
  "$MIN_LINES" "$MIN_BRANCHES" "$MIN_FUNCTIONS"
printf 'Results: %d passed, %d failed, %d skipped\n' "$PASS" "$FAIL" "$SKIP"
printf '\n'

if [ "$FAIL" -gt 0 ]; then
  printf 'Coverage gate FAILED — raise test coverage or lower thresholds via NEAREST_NEIGHBOR_COVERAGE_MIN_* env vars.\n' >&2
  exit 1
fi

printf 'Coverage gate passed.\n'
